# https://taskfile.dev

version: '3'

tasks:
  default:
    desc: List all tasks
    cmds:
      - go tool task --list
    silent: true

  lint:
    desc: Run golangci-lint
    cmds:
      - go tool golangci-lint run

  test:e2e:
    desc: Run end-to-end tests
    cmds:
      - go tool runn run --scopes read:parent ./tests/e2e/*.yml
