# https://taskfile.dev

version: '3'

tasks:
  default:
    desc: List all tasks
    cmds:
      - go tool task --list
    silent: true

  generate:
    desc: Generate Code from OpenAPI spec
    cmds:
      - go tool oapi-codegen -config config.yml openapi.yml
    silent: true

  lint:
    desc: Run golangci-lint
    cmds:
      - go tool golangci-lint run

  test:api:
    desc: Run API tests
    cmds:
      - go tool runn run --scopes read:parent ./tests/e2e/*.yml
