# https://taskfile.dev

version: '3'

tasks:
  lint:
    desc: Run golangci-lint
    cmds:
      - go tool golangci-lint run

  test:e2e:
    desc: Run end-to-end tests
    cmds:
      - go tool runn run ./tests/e2e/*.yml
