// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"time"
)

// AuthRequest defines model for AuthRequest.
type AuthRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Task defines model for Task.
type Task struct {
	Completed bool      `json:"completed"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
}

// TaskCreateRequest defines model for TaskCreateRequest.
type TaskCreateRequest struct {
	Content string `json:"content"`
}

// Token defines model for Token.
type Token struct {
	Token string `json:"token"`
}

// User defines model for User.
type User struct {
	Email string `json:"email"`
	Id    int    `json:"id"`
	Name  string `json:"name"`
}

// UserCreateRequest defines model for UserCreateRequest.
type UserCreateRequest struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

// PostAuthJSONRequestBody defines body for PostAuth for application/json ContentType.
type PostAuthJSONRequestBody = AuthRequest

// PostTasksJSONRequestBody defines body for PostTasks for application/json ContentType.
type PostTasksJSONRequestBody = TaskCreateRequest

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody = UserCreateRequest
